Add function to switch options

diff --git a/lftp-directory b/lftp-directory
--- a/lftp-directory
+++ b/lftp-directory
@@ -1,5 +1,13 @@
 #!/bin/bash
- 
+
+# TODO
+# + unify logic to parse arguments into parameters
+#   (hostname and path is done in main process, however
+#    option is done in function)
+# + implement debug function
+# + implement other function except mirror
+
+
 __lftp="/usr/bin/lftp"
 __whoami="/usr/bin/whoami"
 
@@ -7,6 +15,17 @@ __whoami="/usr/bin/whoami"
 
 for __ in "$(dirname $0)/lib-"* ; do . "${__}" ; done
 
+
+
+check_bash_version()
+{
+    if [ "${BASH_VERSINFO[0]}" = "4" ] || [ "${BASH_VERSINFO[0]}" -gt "4" ]
+    then
+        return ${EXITCODE_NO_ERROR}
+    else
+        return ${EXITCODE_ERROR}
+    fi
+}
 
 
 check_binary()
@@ -18,12 +37,30 @@ check_binary()
 }
 
 
+exit_error()
+{
+    exit ${EXITCODE_ERROR}
+}
+
+
+exit_no_error()
+{
+    exit ${EXITCODE_NO_ERROR}
+
+}
+
+
 show_usage()
 {
     cat <<TXT
-Usage: $0 -s source_description -d destination_description
+Usage: ${0} -s source_description -d destination_description [ -o options_description ]
     Local Description: \${LOCAL_PATH}
     Remote Description: [\${REMOTE_USER}[:\${REMOTE_PASSWORD}]@]\${REMOTE_HOST}[:\${REMOTE_PORT}]:[\${REMOTE_PATH}]
+    Options Description: \${OPT_KEY}=\${OPT_VALUE}
+        PassiveMode=[on|off] (off is default)
+        ForceSSL=[on|off] (on is default)
+        AllowSSL=[on|off] (on is default)
+        VerifySSLCert=[on|off] (off is default)
 TXT
     exit ${EXITCODE_WARNING}
 }
@@ -31,12 +68,44 @@ TXT
 
 generate_setting_command()
 {
+    local _opts="${@}"
+
+    local _passive_mode="off"
+    local _force_ssl="on"
+    local _allow_ssl="on"
+    local _verify_ssl_cert="off"
+
+    for _opt in ${_opts}
+    do
+        if [[ "${_opt}" =~ ^([^=]+)=([^=]+)$ ]]
+        then
+            local _k="${BASH_REMATCH[1]}"
+            local _v="${BASH_REMATCH[2]}"
+
+            [ "${_k,,}" = "passivemode" ] && [[ "${_v,,}" =~ ^(on|off)$ ]] &&
+                _passive_mode="${BASH_REMATCH[1]}"
+
+            [ "${_k,,}" = "forcessl" ] && [[ "${_v,,}" =~ ^(on|off)$ ]] &&
+                _force_ssl="${BASH_REMATCH[1]}"
+                    
+            [ "${_k,,}" = "allowssl" ] && [[ "${_v,,}" =~ ^(on|off)$ ]] &&
+                _allow_ssl="${BASH_REMATCH[1]}"
+
+            [ "${_k,,}" = "verifysslcert" ] && [[ "${_v,,}" =~ ^(on|off)$ ]] &&
+                _verify_ssl_cert="${BASH_REMATCH[1]}"
+        fi
+    done
+
+    local _protect_data="on"
+    [ "${_force_ssl}" = "off" -a "${_allow_ssl}" = "off" ] &&
+        _protect_data="off"
+
     cat <<CMD
-set ftp:passive-mode off
-set ftp:ssl-force on
-set ftp:ssl-allow on
-set ftp:ssl-protect-data on
-set ssl:verify-certificate off
+set ftp:passive-mode ${_passive_mode}
+set ftp:ssl-force ${_force_ssl}
+set ftp:ssl-allow ${_allow_ssl}
+set ftp:ssl-protect-data ${_protect_data}
+set ssl:verify-certificate ${_verify_ssl_cert}
 CMD
 
     return ${EXITCODE_NO_ERROR}
@@ -143,10 +212,21 @@ generate_mirror_remote_command()
 
 
 
+# MAIN PROCESS
+[ ! check_bash_version ] &&
+    log_err_message "Bash version must be equal of more than 4." &&
+    exit_error
+
+[ ! check_binary ] &&
+    log_err_message "Required binary file is not found." &&
+    exit_error
+
+
 _desc_src=
 _desc_dst=
+_desc_opt=
 
-while getopts s:d: OPT
+while getopts s:d:o: OPT
 do
     case "${OPT}" in
     s)
@@ -155,11 +235,14 @@ do
     d)
         _desc_dst="${OPTARG}"
         ;;
+    o)
+        _desc_opt="${OPTARG}${_desc_opt:+ }${_desc_opt}"
     esac
 done
 
 #echo "SRC_DESC = ${_desc_src}"
 #echo "DST_DESC = ${_desc_dst}"
+#echo "OPT_DESC = ${_desc_opt}"
 
 
 _username=
@@ -199,11 +282,6 @@ fi
 #echo "IS_R_2_L = ${_remote_to_local}"
 
 
-
-# MAIN PROCESS
-check_binary || ( _result=$?; echo "Required binary file is not found."; exit ${_result} )
-
-
 if [ -z "${_username}" ]
 then
     _username=$(${__whoami})
@@ -215,13 +293,13 @@ fi
 
 if [ -z "${_password}" ]
 then
-    log_err_message "Password is not specified." && exit ${EXITCODE_ERROR}
+    log_err_message "Password is not specified." && exit_error
 fi
 
 
 if [ -z "${_hostname}" ]
 then
-    log_err_message "Hostname is not specified." && exit ${EXITCODE_ERROR}
+    log_err_message "Hostname is not specified." && exit_error
 fi
 
 
@@ -230,7 +308,7 @@ then
     log_info_message "Port number is not specified, so default is used."
 elif [[ ! "${_portnum}" =~ ^[0-9]{1,}$ ]]
 then
-    log_err_message "Specified port \"${_portnum}\" is not invalid." && exit ${EXITCODE_ERROR}
+    log_err_message "Specified port \"${_portnum}\" is not invalid." && exit_error
 else
     log_info_message "Specified port \"${_portnum}\" is used."
 fi
@@ -246,14 +324,14 @@ then
     log_info_message "Destination directory is \"${_hostname}:${_path_dst}\"."
 else
     log_err_message "Unknown error occured when parsing arguments."
-    exit ${EXITCODE_ERROR}
+    exit_error
 fi
 
 
 log_info_message "Mirroring is started."
 
 if (
-    generate_setting_command
+    generate_setting_command "${_desc_opt}"
     generate_connect_command "${_username}" "${_password}" "${_hostname}" "${_portnum}"
     #generate_list_remote_command
 
@@ -267,8 +345,8 @@ if (
     generate_end_command
 ) | ${__lftp}
 then
-    log_info_message "Mirroring is finished with no error." && exit ${EXITCODE_NO_ERROR}
+    log_info_message "Mirroring is finished with no error." && exit_no_error
 else
-    log_err_message "Mirroring is aborted with error(s)." && exit ${EXITCODE_ERORR}
+    log_err_message "Mirroring is aborted with error(s)." && exit_error
 fi
 
